spring:
  main:
    banner-mode: "off"
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/aprilskindb?useUnicode=true&characterEncoding=utf8"
    username: root
    password: password
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true


