spring:
  main:
    banner-mode: "off"
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/aprilskindb"
    username: root
    password: password
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

---
spring:
  profiles: prd
logging :
  file : logs/prd_app.log
  pattern:
    file :  "%d{yyyy-MM-dd HH:mm:ss}%msg%n"
  level:
    org.springframework.web: INFO
    april_spring_boot.springframework.controllers: INFO
    org.hibernate : INFO