spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
